import type { CarListing, Seller, Testimonial, PricingTier, FAQ, Stat, CarCategory, DashboardStat, Transaction } from '../types';

export const carListings: CarListing[] = [
  {
    id: '1',
    title: '2023 BMW M4 Competition xDrive',
    brand: 'BMW',
    model: 'M4 Competition',
    year: 2023,
    price: 89500,
    mileage: 4200,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    condition: 'Certified Pre-Owned',
    color: 'Portimao Blue',
    location: 'Miami, FL',
    category: 'Sports',
    imageColor: 'from-blue-600 to-blue-900',
    badge: 'Featured',
    rating: 4.9,
    reviewCount: 34,
    sellerId: '1',
    description: 'Immaculate M4 with full factory options including carbon fiber roof, M Driver Package, and Heads-Up Display. One owner, dealer serviced.',
    features: ['Carbon Fiber Roof', 'M Adaptive Suspension', 'Harman Kardon Audio', 'Heads-Up Display', 'M Driver Package', 'Heated Seats'],
    daysOnMarket: 3,
  },
  {
    id: '2',
    title: '2024 Tesla Model S Plaid',
    brand: 'Tesla',
    model: 'Model S Plaid',
    year: 2024,
    price: 109990,
    mileage: 1800,
    fuelType: 'Electric',
    transmission: 'Automatic',
    condition: 'New',
    color: 'Midnight Silver',
    location: 'Los Angeles, CA',
    category: 'Electric',
    imageColor: 'from-gray-600 to-gray-900',
    badge: 'New Arrival',
    rating: 4.8,
    reviewCount: 21,
    sellerId: '2',
    description: 'The quickest production car ever made. 0-60 in under 2 seconds. Full Self-Driving capability included.',
    features: ['Full Self-Driving', 'Tri-Motor AWD', '21" Arachnid Wheels', 'Premium Audio', 'Glass Roof', 'Yoke Steering'],
    daysOnMarket: 1,
  },
  {
    id: '3',
    title: '2022 Porsche 911 Carrera 4S',
    brand: 'Porsche',
    model: '911 Carrera 4S',
    year: 2022,
    price: 142000,
    mileage: 9800,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    condition: 'Certified Pre-Owned',
    color: 'Guards Red',
    location: 'Chicago, IL',
    category: 'Sports',
    imageColor: 'from-red-600 to-red-900',
    badge: 'Hot Deal',
    rating: 5.0,
    reviewCount: 18,
    sellerId: '1',
    description: 'Pristine Guards Red 992 with Sport Chrono Package, PASM, and PDLS Plus lighting. Porsche Approved Certified.',
    features: ['Sport Chrono Package', 'PASM Sport Suspension', 'Bose Surround Sound', 'Lane Change Assist', 'PDLS Plus', 'Sport Exhaust'],
    daysOnMarket: 7,
  },
  {
    id: '4',
    title: '2023 Mercedes-Benz GLE 450 AMG Line',
    brand: 'Mercedes-Benz',
    model: 'GLE 450',
    year: 2023,
    price: 74900,
    mileage: 12400,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    condition: 'Certified Pre-Owned',
    color: 'Obsidian Black',
    location: 'Houston, TX',
    category: 'SUV',
    imageColor: 'from-gray-800 to-black',
    badge: 'Certified',
    rating: 4.7,
    reviewCount: 29,
    sellerId: '3',
    description: 'Fully loaded GLE with AMG Line package, Burmester sound system, and MBUX with augmented reality navigation.',
    features: ['AMG Line Exterior', 'Burmester 3D Sound', 'MBUX AR Navigation', 'Airmatic Suspension', 'Panoramic Sunroof', '360° Camera'],
    daysOnMarket: 12,
  },
  {
    id: '5',
    title: '2024 Ford Mustang GT500 Shelby',
    brand: 'Ford',
    model: 'Mustang Shelby GT500',
    year: 2024,
    price: 98700,
    mileage: 650,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    condition: 'New',
    color: 'Race Red',
    location: 'Dallas, TX',
    category: 'Sports',
    imageColor: 'from-red-500 to-orange-700',
    badge: 'New Arrival',
    rating: 4.9,
    reviewCount: 11,
    sellerId: '4',
    description: '760HP supercharged V8 beast. Carbon fiber track package, recaro seats. The pinnacle of American muscle.',
    features: ['760HP Supercharged V8', 'Carbon Fiber Track Package', 'Recaro Seats', 'MagneRide Suspension', 'Brembo Brakes', 'Launch Control'],
    daysOnMarket: 2,
  },
  {
    id: '6',
    title: '2022 Range Rover Autobiography LWB',
    brand: 'Land Rover',
    model: 'Range Rover Autobiography',
    year: 2022,
    price: 167000,
    mileage: 18200,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    condition: 'Certified Pre-Owned',
    color: 'Santorini Black',
    location: 'New York, NY',
    category: 'Luxury SUV',
    imageColor: 'from-slate-700 to-slate-950',
    badge: 'Featured',
    rating: 4.8,
    reviewCount: 16,
    sellerId: '2',
    description: 'Long-wheelbase Autobiography with executive rear seating, rear-seat entertainment, and Meridian Reference Sound.',
    features: ['Executive Rear Seating', 'Meridian Reference Sound', 'Rear Entertainment', 'Pixel LED Headlights', 'Soft Close Doors', 'Wade Sensing'],
    daysOnMarket: 9,
  },
  {
    id: '7',
    title: '2023 Audi RS6 Avant Performance',
    brand: 'Audi',
    model: 'RS6 Avant',
    year: 2023,
    price: 129500,
    mileage: 6700,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    condition: 'Certified Pre-Owned',
    color: 'Nardo Gray',
    location: 'Seattle, WA',
    category: 'Wagon',
    imageColor: 'from-zinc-500 to-zinc-800',
    badge: 'Hot Deal',
    rating: 4.9,
    reviewCount: 22,
    sellerId: '3',
    description: 'The ultimate family super-wagon. 630HP, quattro AWD, air suspension. Nardo Gray with black optics package.',
    features: ['630HP Twin-Turbo V8', 'Quattro AWD', 'Air Suspension', 'Night Vision', 'Bang & Olufsen Sound', 'Carbon Ceramics'],
    daysOnMarket: 5,
  },
  {
    id: '8',
    title: '2024 Chevrolet Corvette Z06',
    brand: 'Chevrolet',
    model: 'Corvette Z06',
    year: 2024,
    price: 115000,
    mileage: 320,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    condition: 'New',
    color: 'Rapid Blue',
    location: 'Nashville, TN',
    category: 'Sports',
    imageColor: 'from-blue-500 to-cyan-700',
    badge: 'New Arrival',
    rating: 4.8,
    reviewCount: 9,
    sellerId: '4',
    description: '670HP flat-plane crank V8. The most powerful naturally aspirated V8 in a production car. Z07 Performance Package included.',
    features: ['670HP Flat-Plane V8', 'Z07 Performance Package', 'Brembo Carbon Ceramic Brakes', 'Magnetic Ride 4.0', 'GT2 Seats', 'FE4 Suspension'],
    daysOnMarket: 1,
  },
];

export const sellers: Seller[] = [
  {
    id: '1',
    name: 'Prestige Auto Gallery',
    type: 'Dealership',
    location: 'Miami, FL',
    rating: 4.9,
    reviewCount: 847,
    totalSales: 2340,
    memberSince: 'March 2019',
    verified: true,
    avatarInitials: 'PA',
    avatarColor: 'from-orange-500 to-red-600',
    speciality: 'European Luxury & Sports Cars',
    phone: '+1 (305) 555-0142',
    email: 'sales@prestigeautogallery.com',
  },
  {
    id: '2',
    name: 'Elite Motors LA',
    type: 'Dealership',
    location: 'Los Angeles, CA',
    rating: 4.8,
    reviewCount: 612,
    totalSales: 1890,
    memberSince: 'January 2018',
    verified: true,
    avatarInitials: 'EM',
    avatarColor: 'from-violet-500 to-indigo-600',
    speciality: 'Tesla & Electric Vehicles',
    phone: '+1 (310) 555-0198',
    email: 'info@elitemotorsla.com',
  },
  {
    id: '3',
    name: 'Velocity Auto Group',
    type: 'Dealership',
    location: 'Houston, TX',
    rating: 4.7,
    reviewCount: 423,
    totalSales: 1240,
    memberSince: 'June 2020',
    verified: true,
    avatarInitials: 'VA',
    avatarColor: 'from-emerald-500 to-teal-600',
    speciality: 'German Performance Vehicles',
    phone: '+1 (713) 555-0167',
    email: 'sales@velocityauto.com',
  },
  {
    id: '4',
    name: 'Marcus Thompson',
    type: 'Private Seller',
    location: 'Dallas, TX',
    rating: 5.0,
    reviewCount: 31,
    totalSales: 28,
    memberSince: 'August 2021',
    verified: true,
    avatarInitials: 'MT',
    avatarColor: 'from-amber-500 to-orange-600',
    speciality: 'American Muscle & Performance',
    phone: '+1 (214) 555-0183',
    email: 'm.thompson@email.com',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Rafael Mendoza',
    role: 'General Manager',
    company: 'Prestige Auto Gallery, Miami',
    avatar: 'RM',
    avatarColor: 'from-orange-400 to-red-500',
    rating: 5,
    quote: "AutoMarket Pro transformed how we do business. We listed 47 vehicles in one afternoon and received qualified leads within hours. Our monthly sales revenue went up 38% in the first 90 days. The dashboard analytics tell us exactly which listings are converting and why.",
  },
  {
    id: '2',
    name: 'Samantha Okafor',
    role: 'Co-founder',
    company: 'Velocity Auto Group, Houston',
    avatar: 'SO',
    avatarColor: 'from-violet-400 to-purple-600',
    rating: 5,
    quote: "I was skeptical about moving our inventory online, but the AutoMarket Pro team made the transition seamless. The verified seller badge gave our buyers confidence, and we closed 3 deals in the first week without a single in-person visit. Absolutely game-changing for our dealership.",
  },
  {
    id: '3',
    name: 'Derek Whitfield',
    role: 'Private Collector',
    company: 'Nashville, Tennessee',
    avatar: 'DW',
    avatarColor: 'from-emerald-400 to-teal-600',
    rating: 5,
    quote: "Sold my 911 Carrera for $4,000 above my asking price because the platform connected me with three serious buyers who were competing for it. The secure messaging and escrow payment system made the whole process stress-free. I'll never use another platform.",
  },
];

export const pricingTiers: PricingTier[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: 49,
    period: 'month',
    description: 'Perfect for private sellers and small lots getting started.',
    featured: false,
    cta: 'Start Free Trial',
    features: [
      { text: 'Up to 5 active listings', included: true },
      { text: 'Photo uploads (10 per listing)', included: true },
      { text: 'Basic analytics dashboard', included: true },
      { text: 'Buyer messaging inbox', included: true },
      { text: 'AutoMarket verified badge', included: false },
      { text: 'Featured listing placement', included: false },
      { text: 'Advanced lead management', included: false },
    ],
  },
  {
    id: 'professional',
    name: 'Professional',
    price: 149,
    period: 'month',
    description: 'Built for growing dealerships ready to scale their online presence.',
    featured: true,
    cta: 'Start Free Trial',
    features: [
      { text: 'Up to 50 active listings', included: true },
      { text: 'Unlimited photo uploads', included: true },
      { text: 'Advanced analytics & insights', included: true },
      { text: 'Priority buyer messaging', included: true },
      { text: 'AutoMarket verified badge', included: true },
      { text: 'Featured listing placement', included: true },
      { text: 'Advanced lead management', included: false },
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 399,
    period: 'month',
    description: 'Full-power platform for large dealerships and auto groups.',
    featured: false,
    cta: 'Contact Sales',
    features: [
      { text: 'Unlimited active listings', included: true },
      { text: 'Unlimited photo uploads', included: true },
      { text: 'Real-time analytics suite', included: true },
      { text: 'Priority buyer messaging', included: true },
      { text: 'AutoMarket verified badge', included: true },
      { text: 'Featured listing placement', included: true },
      { text: 'Advanced lead management CRM', included: true },
    ],
  },
];

export const faqs: FAQ[] = [
  {
    id: '1',
    question: 'How quickly can I list my vehicle after signing up?',
    answer: 'You can have your first listing live in under 10 minutes. Simply complete your seller verification (which takes about 2-3 minutes), add your vehicle details, upload photos, and set your price. Our AI-assisted listing tool even suggests competitive pricing based on current market data.',
  },
  {
    id: '2',
    question: 'What does the AutoMarket Verified badge mean for sellers?',
    answer: 'The Verified badge means we have confirmed your identity, business license (for dealerships), and vehicle title ownership. Verified listings receive 3x more buyer inquiries on average and appear higher in search results, dramatically improving your sell-through rate.',
  },
  {
    id: '3',
    question: 'How does payment and escrow work for private transactions?',
    answer: 'Our secure escrow system holds the buyer\'s funds during the vehicle inspection period (up to 72 hours). Once the buyer confirms satisfaction, funds are released to you within 1-2 business days. This protects both parties and eliminates the risk of fraud or payment disputes.',
  },
  {
    id: '4',
    question: 'Can I manage multiple dealership locations from one account?',
    answer: 'Yes — Enterprise plans support multi-location management with separate inventory views, location-specific analytics, and team member access controls. Each location gets its own branded profile while sharing a single unified dashboard for ownership oversight.',
  },
  {
    id: '5',
    question: 'What types of vehicles can be listed on AutoMarket Pro?',
    answer: 'We support cars, trucks, SUVs, motorcycles, RVs, boats, and commercial vehicles. Each category has tailored listing fields so buyers get the exact information they need. Electric and hybrid vehicles have dedicated battery health and range fields.',
  },
  {
    id: '6',
    question: 'Is there a contract or can I cancel my plan anytime?',
    answer: 'All plans are month-to-month with no long-term contracts. You can upgrade, downgrade, or cancel at any time from your account settings. If you cancel, your listings remain active until the end of your paid period. Annual plans receive a 20% discount and come with priority onboarding.',
  },
  {
    id: '7',
    question: 'What analytics does the seller dashboard provide?',
    answer: 'Your dashboard shows listing view counts, save/watchlist additions, inquiry conversion rates, price comparison against similar vehicles, and 30/60/90-day market trend data. Professional and Enterprise plans also include buyer demographic insights and search keyword performance.',
  },
];

export const stats: Stat[] = [
  { label: 'Vehicles Sold', value: '48,200', suffix: '+', description: 'successful transactions' },
  { label: 'Active Listings', value: '12,400', suffix: '+', description: 'vehicles right now' },
  { label: 'Avg. Days to Sell', value: '11', suffix: ' days', description: 'vs. 47 days industry avg.' },
  { label: 'Seller Rating', value: '4.9', suffix: '★', description: 'from 8,600+ reviews' },
];

export const carCategories: CarCategory[] = [
  { name: 'Sports & Performance', count: 1847, icon: '🏎️', color: 'bg-red-50 border-red-100' },
  { name: 'Luxury Sedans', count: 2340, icon: '🚗', color: 'bg-blue-50 border-blue-100' },
  { name: 'SUVs & Crossovers', count: 4120, icon: '🚙', color: 'bg-green-50 border-green-100' },
  { name: 'Electric Vehicles', count: 980, icon: '⚡', color: 'bg-yellow-50 border-yellow-100' },
  { name: 'Trucks & Pickups', count: 1560, icon: '🛻', color: 'bg-orange-50 border-orange-100' },
  { name: 'Convertibles', count: 630, icon: '🌞', color: 'bg-purple-50 border-purple-100' },
];

export const dashboardStats: DashboardStat[] = [
  { label: 'Total Revenue', value: '$284,700', change: '+18.4%', positive: true, icon: 'dollar' },
  { label: 'Active Listings', value: '23', change: '+4', positive: true, icon: 'list' },
  { label: 'New Inquiries', value: '47', change: '+12', positive: true, icon: 'message' },
  { label: 'Avg. List Price', value: '$52,400', change: '-2.1%', positive: false, icon: 'tag' },
];

export const transactions: Transaction[] = [
  { id: 'TXN-001', car: '2023 BMW M4 Competition', buyer: 'James Cartwright', amount: 89500, date: '2024-07-08', status: 'Completed' },
  { id: 'TXN-002', car: '2022 Porsche 911 Carrera', buyer: 'Priya Nandakumar', amount: 142000, date: '2024-07-07', status: 'Completed' },
  { id: 'TXN-003', car: '2024 Tesla Model S Plaid', buyer: 'Carlos Restrepo', amount: 109990, date: '2024-07-06', status: 'Processing' },
  { id: 'TXN-004', car: '2023 Mercedes GLE 450', buyer: 'Aisha Kowalczyk', amount: 74900, date: '2024-07-05', status: 'Completed' },
  { id: 'TXN-005', car: '2023 Audi RS6 Avant', buyer: 'Nathan Bergstrom', amount: 129500, date: '2024-07-04', status: 'Pending' },
  { id: 'TXN-006', car: '2024 Ford Shelby GT500', buyer: 'Olivia Harrington', amount: 98700, date: '2024-07-03', status: 'Completed' },
];